backend:
  name: git-gateway
  branch: main # ya master, jo bhi aapki repository ki default branch hai

media_folder: "images"
public_folder: "/images"

collections:
  - name: "properties"
    label: "Properties"
    folder: "properties"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
